### ISSUE TITLE
Demo site seems dead

### ISSUE THREAD

**Issue by bonjour81** [alphabet5/archery-sight-tape#1]
Hello,
I cannot access demo website (and was not able to build docker image neither)

**Comment by bonjour81** [comment]
Infact it's the link below the screenshot in read file that is :
https://sight-tape.aphabet5.dev/

Missing "l" in a_l_phabet

**Comment by alphabet5** [comment]
Should be fixed now. Thanks. I'm not sure why you wouldn't be able to build the docker image. I'm not really maintaining this now as https://www.precisioncutarchery.com/ is about a million times better.

**Comment by bonjour81** [comment]
Thanks!
Well...the great advantage of your solution (in my opinion): it's free !
I'm not searching for sight tape 'predictive' tool (based on arrow and speed or whatever).
I just look for clean way to print the marks I checked my self => so with some excel table using trend line and your tool, it's fine :)
There are not so much free tools to print sight tape.
